<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<!DOCTYPE hierarchy [
        <!ELEMENT hierarchy (node)*>
        <!ATTLIST hierarchy
                rotation CDATA #REQUIRED>
        <!ELEMENT node (node)*>
        <!ATTLIST node
                NAF CDATA #IMPLIED
                bounds CDATA #REQUIRED
                checkable CDATA #REQUIRED
                checked CDATA #REQUIRED
                class CDATA #REQUIRED
                clickable CDATA #REQUIRED
                content-desc CDATA #REQUIRED
                enabled CDATA #REQUIRED
                focusable CDATA #REQUIRED
                focused CDATA #REQUIRED
                index CDATA #REQUIRED
                long-clickable CDATA #REQUIRED
                package CDATA #REQUIRED
                password CDATA #REQUIRED
                resource-id CDATA #REQUIRED
                scrollable CDATA #REQUIRED
                selected CDATA #REQUIRED
                text CDATA #REQUIRED>
        ]>
<hierarchy rotation="0">
    <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.xueqiu.android"
          content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false"
          focused="false" scrollable="false" long-clickable="false" password="false" selected="false"
          bounds="[0,0][1440,2392]">
        <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.xueqiu.android"
              content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false"
              focused="false" scrollable="false" long-clickable="false" password="false" selected="false"
              bounds="[0,0][1440,2392]">
            <node index="0" text="" resource-id="" class="android.widget.ImageView" package="com.xueqiu.android"
                  content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false"
                  focused="false" scrollable="false" long-clickable="false" password="false" selected="false"
                  bounds="[0,0][15,2392]"/>
            <node index="1" text="" resource-id="" class="android.widget.LinearLayout" package="com.xueqiu.android"
                  content-desc="" checkable="false" checked="false" clickable="false" enabled="true" focusable="false"
                  focused="false" scrollable="false" long-clickable="false" password="false" selected="false"
                  bounds="[0,0][1440,2392]">
                <node index="0" text="" resource-id="" class="android.widget.FrameLayout" package="com.xueqiu.android"
                      content-desc="" checkable="false" checked="false" clickable="false" enabled="true"
                      focusable="false" focused="false" scrollable="false" long-clickable="false" password="false"
                      selected="false" bounds="[0,0][1440,2392]">
                    <node index="0" text="" resource-id="com.xueqiu.android:id/decor_content_parent"
                          class="android.view.ViewGroup" package="com.xueqiu.android" content-desc="" checkable="false"
                          checked="false" clickable="false" enabled="true" focusable="false" focused="false"
                          scrollable="false" long-clickable="false" password="false" selected="false"
                          bounds="[0,0][1440,2392]">
                        <node index="0" text="" resource-id="android:id/content" class="android.widget.FrameLayout"
                              package="com.xueqiu.android" content-desc="" checkable="false" checked="false"
                              clickable="false" enabled="true" focusable="false" focused="false" scrollable="false"
                              long-clickable="false" password="false" selected="false" bounds="[0,0][1440,2392]">
                            <node index="0" text=""
                                  resource-id="com.xueqiu.android:id/statusbarutil_fake_status_bar_view"
                                  class="android.view.View" package="com.xueqiu.android" content-desc=""
                                  checkable="false" checked="false" clickable="false" enabled="true" focusable="false"
                                  focused="false" scrollable="false" long-clickable="false" password="false"
                                  selected="false" bounds="[0,0][1440,84]"/>
                            <node index="1" text="" resource-id="" class="android.widget.LinearLayout"
                                  package="com.xueqiu.android" content-desc="" checkable="false" checked="false"
                                  clickable="false" enabled="true" focusable="false" focused="false" scrollable="false"
                                  long-clickable="false" password="false" selected="false" bounds="[0,84][1440,2392]">
                                <node index="0" text="" resource-id="com.xueqiu.android:id/stock_detail_action_bar"
                                      class="android.widget.RelativeLayout" package="com.xueqiu.android" content-desc=""
                                      checkable="false" checked="false" clickable="false" enabled="true"
                                      focusable="false" focused="false" scrollable="false" long-clickable="false"
                                      password="false" selected="false" bounds="[0,84][1440,252]">
                                    <node index="0" text="" resource-id="" class="android.widget.LinearLayout"
                                          package="com.xueqiu.android" content-desc="" checkable="false" checked="false"
                                          clickable="false" enabled="true" focusable="false" focused="false"
                                          scrollable="false" long-clickable="false" password="false" selected="false"
                                          bounds="[0,84][1440,252]">
                                        <node NAF="true" index="0" text=""
                                              resource-id="com.xueqiu.android:id/action_back"
                                              class="android.widget.RelativeLayout" package="com.xueqiu.android"
                                              content-desc="" checkable="false" checked="false" clickable="true"
                                              enabled="true" focusable="false" focused="false" scrollable="false"
                                              long-clickable="false" password="false" selected="false"
                                              bounds="[0,84][215,252]">
                                            <node index="0" text="" resource-id="" class="android.widget.ImageView"
                                                  package="com.xueqiu.android" content-desc="" checkable="false"
                                                  checked="false" clickable="false" enabled="true" focusable="false"
                                                  focused="false" scrollable="false" long-clickable="false"
                                                  password="false" selected="false" bounds="[65,126][149,210]"/>
                                        </node>
                                        <node index="1" text="" resource-id="com.xueqiu.android:id/action_bar_title"
                                              class="android.widget.LinearLayout" package="com.xueqiu.android"
                                              content-desc="" checkable="false" checked="false" clickable="false"
                                              enabled="true" focusable="false" focused="false" scrollable="false"
                                              long-clickable="false" password="false" selected="false"
                                              bounds="[215,84][1224,252]">
                                            <node index="0" text="" resource-id="com.xueqiu.android:id/ll_title_content"
                                                  class="android.widget.LinearLayout" package="com.xueqiu.android"
                                                  content-desc="" checkable="false" checked="false" clickable="false"
                                                  enabled="true" focusable="false" focused="false" scrollable="false"
                                                  long-clickable="false" password="false" selected="false"
                                                  bounds="[215,84][1224,252]">
                                                <node index="0" text="阿里巴巴-SW"
                                                      resource-id="com.xueqiu.android:id/action_bar_stock_name"
                                                      class="android.widget.TextView" package="com.xueqiu.android"
                                                      content-desc="" checkable="false" checked="false"
                                                      clickable="false" enabled="true" focusable="false" focused="false"
                                                      scrollable="false" long-clickable="false" password="false"
                                                      selected="false" bounds="[215,109][1224,186]"/>
                                                <node index="1" text="" resource-id=""
                                                      class="android.widget.LinearLayout" package="com.xueqiu.android"
                                                      content-desc="" checkable="false" checked="false"
                                                      clickable="false" enabled="true" focusable="false" focused="false"
                                                      scrollable="false" long-clickable="false" password="false"
                                                      selected="false" bounds="[423,186][1015,234]">
                                                    <node index="0" text="09988"
                                                          resource-id="com.xueqiu.android:id/title_bar_symbol"
                                                          class="android.widget.TextView" package="com.xueqiu.android"
                                                          content-desc="" checkable="false" checked="false"
                                                          clickable="false" enabled="true" focusable="false"
                                                          focused="false" scrollable="false" long-clickable="false"
                                                          password="false" selected="false"
                                                          bounds="[423,188][540,231]"/>
                                                    <node index="1" text="已收盘03-12 16:08:30 北京"
                                                          resource-id="com.xueqiu.android:id/action_bar_subtitle"
                                                          class="android.widget.TextView" package="com.xueqiu.android"
                                                          content-desc="" checkable="false" checked="false"
                                                          clickable="false" enabled="true" focusable="false"
                                                          focused="false" scrollable="false" long-clickable="false"
                                                          password="false" selected="false"
                                                          bounds="[551,186][1015,234]"/>
                                                </node>
                                            </node>
                                        </node>
                                        <node NAF="true" index="2" text=""
                                              resource-id="com.xueqiu.android:id/action_search"
                                              class="android.widget.ImageView" package="com.xueqiu.android"
                                              content-desc="" checkable="false" checked="false" clickable="true"
                                              enabled="true" focusable="false" focused="false" scrollable="false"
                                              long-clickable="false" password="false" selected="false"
                                              bounds="[1224,84][1440,252]"/>
                                    </node>
                                    <node index="1" text="" resource-id="" class="android.view.View"
                                          package="com.xueqiu.android" content-desc="" checkable="false" checked="false"
                                          clickable="false" enabled="true" focusable="false" focused="false"
                                          scrollable="false" long-clickable="false" password="false" selected="false"
                                          bounds="[0,251][1440,252]"/>
                                </node>
                                <node index="1" text="" resource-id="" class="android.widget.FrameLayout"
                                      package="com.xueqiu.android" content-desc="" checkable="false" checked="false"
                                      clickable="false" enabled="true" focusable="false" focused="false"
                                      scrollable="false" long-clickable="false" password="false" selected="false"
                                      bounds="[0,252][1440,2392]">
                                    <node index="0" text="" resource-id="com.xueqiu.android:id/viewPager"
                                          class="androidx.viewpager.widget.ViewPager" package="com.xueqiu.android"
                                          content-desc="" checkable="false" checked="false" clickable="false"
                                          enabled="true" focusable="true" focused="false" scrollable="false"
                                          long-clickable="false" password="false" selected="false"
                                          bounds="[0,252][1440,2392]">
                                        <node index="0" text="" resource-id="" class="android.widget.FrameLayout"
                                              package="com.xueqiu.android" content-desc="" checkable="false"
                                              checked="false" clickable="false" enabled="true" focusable="false"
                                              focused="false" scrollable="false" long-clickable="false" password="false"
                                              selected="false" bounds="[0,252][1440,2392]">
                                            <node index="1" text="" resource-id="" class="android.widget.RelativeLayout"
                                                  package="com.xueqiu.android" content-desc="" checkable="false"
                                                  checked="false" clickable="false" enabled="true" focusable="false"
                                                  focused="false" scrollable="false" long-clickable="false"
                                                  password="false" selected="false" bounds="[0,252][1440,2392]">
                                                <node index="0" text=""
                                                      resource-id="com.xueqiu.android:id/stock_index_quote_view"
                                                      class="android.widget.FrameLayout" package="com.xueqiu.android"
                                                      content-desc="" checkable="false" checked="false"
                                                      clickable="false" enabled="true" focusable="false" focused="false"
                                                      scrollable="false" long-clickable="false" password="false"
                                                      selected="false" bounds="[0,252][1440,2237]">
                                                    <node index="0" text="" resource-id=""
                                                          class="android.widget.LinearLayout"
                                                          package="com.xueqiu.android" content-desc="" checkable="false"
                                                          checked="false" clickable="false" enabled="true"
                                                          focusable="false" focused="false" scrollable="false"
                                                          long-clickable="false" password="false" selected="false"
                                                          bounds="[0,252][1440,2237]">
                                                        <node index="0" text=""
                                                              resource-id="com.xueqiu.android:id/rootView"
                                                              class="android.widget.LinearLayout"
                                                              package="com.xueqiu.android" content-desc=""
                                                              checkable="false" checked="false" clickable="false"
                                                              enabled="true" focusable="false" focused="false"
                                                              scrollable="false" long-clickable="false" password="false"
                                                              selected="false" bounds="[0,252][1440,2237]">
                                                            <node index="0" text=""
                                                                  resource-id="com.xueqiu.android:id/mask_view"
                                                                  class="android.view.View" package="com.xueqiu.android"
                                                                  content-desc="" checkable="false" checked="false"
                                                                  clickable="false" enabled="true" focusable="false"
                                                                  focused="false" scrollable="false"
                                                                  long-clickable="false" password="false"
                                                                  selected="false" bounds="[0,252][1440,2130]"/>
                                                            <node index="1" text="" resource-id=""
                                                                  class="android.widget.FrameLayout"
                                                                  package="com.xueqiu.android" content-desc=""
                                                                  checkable="false" checked="false" clickable="false"
                                                                  enabled="true" focusable="false" focused="false"
                                                                  scrollable="false" long-clickable="false"
                                                                  password="false" selected="false"
                                                                  bounds="[0,2131][1440,2237]">
                                                                <node index="0" text=""
                                                                      resource-id="com.xueqiu.android:id/multi_market_index_pager"
                                                                      class="androidx.viewpager.widget.ViewPager"
                                                                      package="com.xueqiu.android" content-desc=""
                                                                      checkable="false" checked="false"
                                                                      clickable="false" enabled="true" focusable="true"
                                                                      focused="false" scrollable="true"
                                                                      long-clickable="false" password="false"
                                                                      selected="false" bounds="[0,2131][1440,2237]">
                                                                    <node index="1" text=""
                                                                          resource-id="com.xueqiu.android:id/linear"
                                                                          class="android.widget.LinearLayout"
                                                                          package="com.xueqiu.android" content-desc=""
                                                                          checkable="false" checked="false"
                                                                          clickable="false" enabled="true"
                                                                          focusable="false" focused="false"
                                                                          scrollable="false" long-clickable="false"
                                                                          password="false" selected="false"
                                                                          bounds="[0,2131][1440,2237]">
                                                                        <node index="0" text=""
                                                                              resource-id="com.xueqiu.android:id/stock_index_quote_view"
                                                                              class="android.widget.FrameLayout"
                                                                              package="com.xueqiu.android"
                                                                              content-desc="" checkable="false"
                                                                              checked="false" clickable="false"
                                                                              enabled="true" focusable="false"
                                                                              focused="false" scrollable="false"
                                                                              long-clickable="false" password="false"
                                                                              selected="false"
                                                                              bounds="[0,2131][1440,2237]">
                                                                            <node index="0" text="" resource-id=""
                                                                                  class="android.widget.FrameLayout"
                                                                                  package="com.xueqiu.android"
                                                                                  content-desc="" checkable="false"
                                                                                  checked="false" clickable="false"
                                                                                  enabled="true" focusable="false"
                                                                                  focused="false" scrollable="false"
                                                                                  long-clickable="false"
                                                                                  password="false" selected="false"
                                                                                  bounds="[0,2131][1440,2237]">
                                                                                <node index="0" text=""
                                                                                      resource-id="com.xueqiu.android:id/single_line_wrapper"
                                                                                      class="android.widget.LinearLayout"
                                                                                      package="com.xueqiu.android"
                                                                                      content-desc="" checkable="false"
                                                                                      checked="false" clickable="true"
                                                                                      enabled="true" focusable="false"
                                                                                      focused="false" scrollable="false"
                                                                                      long-clickable="false"
                                                                                      password="false" selected="false"
                                                                                      bounds="[0,2131][1440,2237]">
                                                                                    <node index="0" text=""
                                                                                          resource-id=""
                                                                                          class="android.view.View"
                                                                                          package="com.xueqiu.android"
                                                                                          content-desc=""
                                                                                          checkable="false"
                                                                                          checked="false"
                                                                                          clickable="false"
                                                                                          enabled="true"
                                                                                          focusable="false"
                                                                                          focused="false"
                                                                                          scrollable="false"
                                                                                          long-clickable="false"
                                                                                          password="false"
                                                                                          selected="false"
                                                                                          bounds="[0,2131][1440,2132]"/>
                                                                                    <node index="1" text=""
                                                                                          resource-id="com.xueqiu.android:id/single_line_root"
                                                                                          class="android.widget.LinearLayout"
                                                                                          package="com.xueqiu.android"
                                                                                          content-desc=""
                                                                                          checkable="false"
                                                                                          checked="false"
                                                                                          clickable="false"
                                                                                          enabled="true"
                                                                                          focusable="false"
                                                                                          focused="false"
                                                                                          scrollable="false"
                                                                                          long-clickable="false"
                                                                                          password="false"
                                                                                          selected="false"
                                                                                          bounds="[0,2132][1440,2237]">
                                                                                        <node index="0" text=""
                                                                                              resource-id="com.xueqiu.android:id/single_line_flipper_view"
                                                                                              class="android.widget.ViewFlipper"
                                                                                              package="com.xueqiu.android"
                                                                                              content-desc=""
                                                                                              checkable="false"
                                                                                              checked="false"
                                                                                              clickable="false"
                                                                                              enabled="true"
                                                                                              focusable="false"
                                                                                              focused="false"